import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans';
import './globals.css'
import { ResizableBaseLayout } from '@/components/composite/resizable-base-layout';
import { TooltipProvider } from '@/components/ui/tooltip';


export const metadata: Metadata = {
  title: 'Falcon Ai',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
      <div className="flex flex-col min-h-screen">
      <TooltipProvider delayDuration={0}>
        <ResizableBaseLayout >
          {children}
        </ResizableBaseLayout>
        </TooltipProvider>
      </div>
        </body>
    </html>
  )
}
