import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Falcon Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <div className="flex flex-col h-[100vh]">
          <TooltipProvider delayDuration={0}>            
              {children}
          </TooltipProvider>
        </div>
      </body>
    </html>
  );
}
